# regions.py

regions = {
    "Toshkent shahri": ["Toshkent shahri", "Olmazor tumani", "Bektemir tumani", "Mirobod tumani", "Mirzo Ulug'bek tumani", "Sergeli tumani", "Uchtepa tumani", "Chilonzor tumani", "Shayxontohur tumani", "Yunusobod tumani", "Yaqqasaroy tumani", "Yashnobod tumani"],
    "Toshkent viloyati": ["Nurafshon shahri", "Angren shahri", "Bekobod shahri", "Olmaliq shahri", "Ohangaron shahri", "Chirchiq shahri", "Yangiyo'l shahri", "Oqqo'rg'on tumani", "Bostanliq tumani", "Bo'ka tumani", "Zangiota tumani", "Qibray tumani", "Quyi Chirchiq tumani", "O'rta Chirchiq tumani", "Parkent tumani", "Piskent tumani", "Toshkent tumani", "Chinoz tumani", "Yuqori Chirchiq tumani"],
    "Samarqand viloyati": ["Samarqand shahri", "Samarqand tumani", "Bulung'ur tumani", "Urgut tumani", "Jomboy tumani", "Ishtixon tumani", "Kattaqo'rg'on tumani", "Narpay tumani", "Nurobod tumani", "Oqdaryo tumani", "Paxtachi tumani", "Payariq tumani", "Pastdarg'om tumani", "Qo'shrabot tumani", "Toyloq tumani"],
    "Qoraqalpog'iston Respublikasi": ["Amudaryo tumani", "Beruniy tumani", "Bo'zatov tumani", "Ellikqal'a tumani", "Kegeyli tumani", "Mo'ynoq tumani", "Nukus tumani", "Nukus shahri", "Qo'ng'irot tumani", "Qanliko'l tumani", "Qorao'zak tumani", "Shumanay tumani", "Taxtako'pir tumani", "To'rtko'l tumani", "Xo'jayli tumani", "Chimboy tumani"],
    "Andijon viloyati": ["Andijon shahri", "Xonobod shahri", "Andijon tumani", "Asaka tumani", "Baliqchi tumani", "Bo'z tumani", "Buloqboshi tumani", "Izboskan tumani", "Jalaquduq tumani", "Qo'rg'ontepa tumani", "Marhamat tumani", "Oltinko'l tumani", "Paxtaobod tumani", "Shahrixon tumani", "Ulug'nor tumani", "Xo'jaobod tumani"],
    "Buxoro viloyati": ["Buxoro shahri", "Kogon shahri", "Olot tumani", "Buxoro tumani", "Vobkent tumani", "G'ijduvon tumani", "Jondor tumani", "Qorako'l tumani", "Qorovulbozor tumani", "Peshku tumani", "Romitan tumani", "Shofirkon tumani"],
    "Jizzax viloyati": ["Jizzax shahri", "Arnasoy tumani", "Baxmal tumani", "Do'stlik tumani", "Forish tumani", "G'allaorol tumani", "Jizzax tumani", "Mirzacho'l tumani", "Paxtakor tumani", "Yangiobod tumani", "Zafarobod tumani", "Zarbdor tumani", "Zomin tumani"],
    "Qashqadaryo viloyati": ["Qarshi shahri", "Shahrisabz shahri", "Dehqonobod tumani", "G'uzor tumani", "Qamashi tumani", "Qarshi tumani", "Kasbi tumani", "Kitob tumani", "Koson tumani", "Mirishkor tumani", "Muborak tumani", "Nishon tumani", "Shahrisabz tumani", "Chiroqchi tumani", "Yakkabog' tumani"],
    "Navoiy viloyati": ["Navoiy shahri", "Zarafshon shahri", "Karmana tumani", "Konimex tumani", "Navbahor tumani", "Nurata tumani", "Qiziltepa tumani", "Tomdi tumani", "Uchquduq tumani", "Xatirchi tumani"],
    "Namangan viloyati": ["Namangan shahri", "Kosonsoy tumani", "Mingbuloq tumani", "Namangan tumani", "Norin tumani", "Pop tumani", "To'raqo'rg'on tumani", "Uchqo'rg'on tumani", "Uychi tumani", "Yangiqo'rg'on tumani", "Chust tumani", "Chortoq tumani"],
    "Surxondaryo viloyati": ["Termiz shahri", "Angor tumani", "Boysun tumani", "Denov tumani", "Jarqo'rg'on tumani", "Muzrabot tumani", "Oltinsoy tumani", "Qiziriq tumani", "Qumqo'rg'on tumani", "Sariosiyo tumani", "Sherobod tumani", "Sho'rchi tumani", "Termiz tumani", "Uzun tumani"],
    "Sirdaryo viloyati": ["Guliston shahri", "Yangiyer shahri", "Shirin shahri", "Oqoltin tumani", "Boyovut tumani", "Guliston tumani", "Mirzaobod tumani", "Sardoba tumani", "Sirdaryo tumani", "Sayxunobod tumani", "Xovos tumani"],
    "Farg'ona viloyati": ["Farg'ona shahri", "Marg'ilon shahri", "Quvasoy shahri", "Qo'qon shahri", "Bog'dod tumani", "Beshariq tumani", "Buvayda tumani", "Dang'ara tumani", "Oltiariq tumani", "O'zbekiston tumani", "Rishton tumani", "So'x tumani", "Toshloq tumani", "Uchko'prik tumani", "Farg'ona tumani", "Furqat tumani", "Qo'shtepa tumani", "Quva tumani", "Yozyovon tumani"],
    "Xorazm viloyati": ["Urganch shahri", "Xiva shahri", "Bog'ot tumani", "Gurlan tumani", "Qoshko'pir tumani", "Urganch tumani", "Xazarasp tumani", "Xiva tumani", "Xonqa tumani", "Shovot tumani", "Yangiariq tumani", "Yangibozor tumani"]
}